included:
  - eCommunicationBook
excluded:
  - Pods
  - Carthage
disabled_rules:
  - trailing_whitespace
identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - url
    - app
file_length:
  warning: 500
  error: 1200
type_body_length:
 - 200 # warning
 - 300 # error
